# The tunel settings file allows a user to configure their tunel install

# Tunnel home - e.g., the local directory to write tunel/ to, where we store launcher assets
tunel_home: "$HOME"

# And the same for remote assets
tunel_remote_home: "$HOME"

# Tunel spinner for logging
# See https://asciinema.org/a/504268
tunel_spinner: dots

# Working directory for containers, etc.
tunel_remote_work: "$HOME"

# Specific directory for remote sockets (default unset, will go in $HOME/.tunel
tunel_remote_sockets: null

# set a default port to use for ssh
ssh_port: 22

# set a default shell
shell: /bin/bash

# remote port to use (this should be randomly generated unless set here)
remote_port: null

# TODO set as random?
local_port: 7789

# Default ssh config to read from
ssh_config: ~/.ssh/config

# Default directory to store sockets
ssh_sockets: ~/.ssh/sockets

# Additional directories with apps to add (searched in order here)
apps_dirs:
 - $default_apps

# Config for specific launchers
launchers:
  singularity:

    # Add these to the path (e.g., mksquashfs is here)
    paths: 
     - /usr/sbin

    # Key/value pairs
    environment:
     - HELLO=MOTO

  htcondor:
    paths: 
     - /usr/sbin
    memory: 8000
    time: "3:00:00"

  slurm:

    # Add these to the path (e.g., mksquashfs is here)
    paths: 
     - /usr/sbin

    # Defaults
    memory: 8000
    time: "3:00:00"

    # Max number of attempts to get a machine (unset is infinite, all with exponential backoff)
    max_attempts: null

# If random port selection used (random port is null) allow within this range
min_port: 90000
max_port: 99999

# default config editor
config_editor: vim
