# The tunel settings file allows a user to configure their tunel install

# Tunnel home - e.g., the local directory to write tunel/ to, where we store launcher assets
tunel_home: "$HOME"

# And the same for remote assets
tunel_remote_home: "$HOME"

# Working directory for containers, etc.
tunel_remote_work: "$HOME"

# set a default port to use for ssh
ssh_port: 22

# remote port to use (this should be randomly generated unless set here)
remote_port: null
local_port: 4000

# Default ssh config to read from
ssh_config: ~/.ssh/config

# Default directory to store sockets
ssh_sockets: ~/.ssh/sockets

# Additional directories with apps to add (searched in order here)
apps_dirs:
 - $default_apps

# Config for specific launchers
launchers:
  singularity:

    # Add these to the path (e.g., mksquashfs is here)
    paths: 
     - /usr/sbin

    # Key/value pairs
    environment:
     - HELLO=MOTO

  slurm:

    # Add these to the path (e.g., mksquashfs is here)
    paths: 
     - /usr/sbin

    # Defaults
    memory: 8000
    time: "6:00:00"

# If random port selection used (random port is null) allow within this range
min_port: 90000
max_port: 99999

# default config editor
config_editor: vim

# Are the compute nodes isolated from the outside world?
isolated_nodes: false
