### GENERAL SETTINGS ###

# Site settings
title: Tunel Apps
description: "Tunel Apps"
baseurl: "/tunel/_static/apps" #important: start with /
url: ""
docs: https://tunel-apps.github.io/tunel/

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more-->

colors:  #in hex code if not noted else
  primary: "#e32929"
  primary_rgb: "247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#F7F7F7"
  link: "#e32929"
  link_hover: "#01b2fe"
  footer_heading: "#777"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  library:
    output: true
    permalink: /r/:title/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
github: https://github.com/tunel-apps
repo: https://github.com/tunel-apps/tunel
docs: https://tunel-apps.github.io/tunel/
maintainer: "@vsoch"
maintainer_url: https://github.com/tunel-apps
social:
  - title: twitter
    url: https://twitter.com/vsoch

about: "Tunel provides interactions and interfaces for HPC, including applications and launchers"
