launcher: singularity
script: jupyter.sh
description: A singularity jupyter notebook or lab to run directly on a remote (e.g., head node)
needs:
  socket: true
examples: |
  # Run jupyter notebook on login node with custom container
  tunel run-app waffles singularity/socket/jupyter --container=docker://jupyter/datascience-notebook
  # Run Jupyterlab login node (via Singularity container) on open science grid
  tunel run-app osg singularity/socket/jupyter --jupyterlab=true
args:
 - name: container
   description: Change the jupyter container used (default is datascience notebook). Must start with container URI to pull (e.g., docker://)
 - name: jupyterlab
   description: Try running jupyterlab instead (e,g. set to true to enable) 
 - name: modules
   description: comma separated list of modules to load
   split: ","
