name: tunel

on:
  pull_request: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup black linter
        run: conda create --quiet --name black pyflakes

      - name: Check Spelling
        uses: crate-ci/typos@592b36d23c62cb378f6097a292bc902ee73f93ef # version 1.0.4
        with:
          files: ./docs/getting_started/ ./docs/index.rst ./README.md

      - name: Lint python code
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate black
          pip install black
          black --check tunel
          
      - name: Check apps
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate black
          pip install -e .[all]
          tunel list-apps --validate
